import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import SessionProvider from '@/components/SessionProvider';
import { ThemeProvider } from "@mui/material/styles";
import theme from './theme/theme';
import CssBaseline from "@mui/material/CssBaseline";


const inter = Inter({ subsets: ['latin'] })

// Navbar contains (and will contain) basic menu items

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <html lang="en">
        <body>
          <SessionProvider>
            <Navbar/>{children}
          </SessionProvider>
        </body>
      </html>
    </ThemeProvider>
  )
};
