'use client'
import { Inter } from 'next/font/google'
import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image';
import { signIn } from "next-auth/react";
import styles from "../styles/home.module.css";

// creating a login button and attaching a listener to fire signin function

// const Home: NextPage = () => {
//   return (
//       <div className={styles.container}>
//           <Head>
//               <title>Create Next App</title>
//               <meta name="description" content="Generated by create next app"/>
//               <link rel="icon" href="/favicon.ico"/>
//           </Head>

//           <main className={styles.main}>
//               <button onClick={() =>{
//                   signIn();
//               }}>Login</button>
//           </main>

//           <button>Login</button>

//           <footer className={styles.footer}></footer>
//       </div>
//   );
// };

// export default Home;





const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <body className={inter.className}>{children}
            <div className={styles.container}>
                <main className={styles.main}>
                    <button onClick={() =>{
                        signIn();
                    }}>Login
                    </button>
                </main>
                <footer className={styles.footer}></footer>
            </div>
            {children}
        </body>
    </html>
  )
}