# Pull request workflow to run CI on PRs.
# Triggered on opened or reopened pull requests.
# Defines one job that reuses the ci.yml workflow.
# ci.yml will run lint, tests, coverage, build for the PR.

name: CI (on pull-request)
run-name: PR from branch ${{ github.ref }}

# Will run CI workflow on an opened or reopened PR for easy reference. For compilation, unit tests, code coverage etc.
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.tsx' # Run CI on PRs that change .tsx files.
      - '**.ts' # Run CI on PRs that change .ts files.
      - '**.jsx'  # Run CI on PRs that change .jsx files.
      - 'app/**/*' # Run CI on PRs that change files in the app folder.
      - 'components/**/*' # Run CI on PRs that change files in the components folder.
      - 'styles/**/*' # Run CI on PRs that change files in the styles folder.
      - '**/*.md' # Run CI on PRs that change .md files.
      # Add more paths here if needed.
jobs:
  Continuous-Integration:
    name: on pull request
    uses: ./.github/workflows/ci.yml